### PR TITLE
Update to _parse_3ds_header

### PR DESCRIPTION
**Pull request by CompPhysChris**
Now converts the header entries into a dictionary, raw_dict, using _split_header_entry
Current entries in header_dict are filled from raw_dict using pop with default values if the expected string is not found
Any remaining entries in raw_dict are added to header_dict unchanged using update
Also changed _split_header_entry to check for the presence of ';' and split the value if it is found.  Now returns both key_str and val_str

### CODE REVIEW

**Comment by CompPhysChris** [comment]
I ran into a problem with some datasets where some of the expected parameters were missing from the header.  I made the changes here to account to that case in Grid data (.3ds)

**Comment by underchemist** [comment]
Hey @CompPhysChris 
sorry about the long wait. I've taken a look at your request. Setting default values definitely seems smart. I'll take a look at it and get back to you soon hopefully.

**Comment by underchemist** [comment]
Let me know if this is a viable fix to your missing entries problem and i can merge and close this pull request. I took most of what you had in the PR but just cleaned it up a bit to not have such specific default values.

**Comment by CompPhysChris** [comment]
It looks like it addresses most of my problems, but you still discard any left-over entries in the raw_dict.  The users I work with need these extra parameters to be returned either as part of the header_dict or as a separate dictionary.

**Pull request merged**
